[package]
name = "dashboar_starter_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"

futures-channel = "0.3.30"
futures-util = "0.3.30"
tokio = { version = "1.37.0", features = ["full"] }
tokio-tungstenite = "0.21.0"

dashboar = { path = "../../../../dashboar", version = "0.1.0" }
dashboar_starter = { path = "../../lib/dashboar_starter" }

[[bin]]
name = "dashboar_starter_bin"
path = "main.rs"
